### ISSUE TITLE
Initializer exception

### ISSUE THREAD

**Issue by mahabhu** [jderuiter/TLSAttackerConnector#1]
after successfully installing the package, running the connector jar file shows the following error message:

Exception in thread "main" java.lang.ExceptionInInitializerError
        at nl.cypherpunk.tlsattackerconnector.TLSAttackerConnector.initialise(TLSAttackerConnector.java:112)
        at nl.cypherpunk.tlsattackerconnector.TLSAttackerConnector.main(TLSAttackerConnector.java:447)
Caused by: javax.xml.bind.DataBindingException: javax.xml.bind.UnmarshalException: Unable to create an instance of de.rub.nds.tlsattacker.core.config.Config
 - with linked exception:
[java.lang.reflect.InvocationTargetException]
        at javax.xml.bind.JAXB.unmarshal(JAXB.java:211)
        at de.rub.nds.tlsattacker.core.config.ConfigIO.read(ConfigIO.java:61)
        at de.rub.nds.tlsattacker.core.config.Config.createConfig(Config.java:100)
        at de.rub.nds.tlsattacker.core.config.Config.<clinit>(Config.java:92)
        ... 2 more

and many more

what might be the possible reason for this, and how to fix this.

**Comment by jderuiter** [comment]
It's a bit hard to say what the problem is based on this log.

As you might have noticed this project is not actively maintained at the moment and probably uses an outdated version of TLSAttacker anyway.

If you still want to use the project, you could try using Docker as well:
```
docker build -t tlsattackerconnector .
docker run tlsattackerconnector --help
```

**Comment by mahabhu** [comment]
Thanks for the commands. However, this time, after opening an OpenSSL server and running Connector using correct targetHost and targetPort, the log shows the error "Could not load wrokflow trace". Is it because it was unable to connect or are we missing any workflow input? Thanks in advance.

**Comment by jderuiter** [comment]
Not sure, as I cannot reproduce this issue. Are you using the TLS-Attacker version referenced in this repository?

Before we start digging into this further: what would you like to use this project for? As I mentioned this project is not actively maintained and it was developed for a quite specific use case.
